from framework.pipeline.parser import Parser
from framework.pipeline.detector import Detector
from framework.pipeline.extractor import Extractor
from framework.pipeline.analyzer import Analyzer
from framework.pipeline.reporter import Reporter
from datetime import datetime
import json
import os
import subprocess
from web3 import Web3
from openai import OpenAI

# Initialize your Web3 connection
w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8504'))

# Initialize the OpenAI client for KIT SCC KI-Toolbox
KIT_API_KEY = os.getenv("sk-567f8518de5a4b7faf3e90241935550f", "sk-567f8518de5a4b7faf3e90241935550f") 

client = OpenAI(
    api_key=KIT_API_KEY,  
    base_url="https://ki-toolbox.scc.kit.edu/api/v1"
)
model_name = "kit.qwen3.5-397b-A17b"

# --- CONTEXT WINDOW DEFENSE SETTINGS ---
MAX_CONTEXT_TOKENS = 220000  
MAX_CODE_CHARS_PER_CONTRACT = 15000  
MAX_EXECUTION_PATHS_PER_TX = 30     

# Common Ethereum/EVM addresses that do NOT need decompilation
KNOWN_CONTRACTS = {
    "0xC02aaA39b223FE8D0A0e5C4F27ead9083C756Cc2": "WETH (Wrapped Ether) - Standard ERC20",
    "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48": "USDC (Stablecoin) - Standard ERC20 / Proxy",
    "0xdAC17F958D2ee523a2206206994597C13D831ec7": "USDT (Tether) - Standard ERC20",
    "0x6B175474E89094C44Da98b954EedeAC495271d0F": "DAI - Standard ERC20",
    "0x7a250d5630B4cf539739dF2C5dAcb4c659F2488D": "Uniswap V2: Router 2",
    "0xE592427A0D111dCC143684c72896A5e168a3043c": "Uniswap V3: Router",
}

def serialize_custom_objects(obj):
    """
    Helper function to convert custom objects (like CallNode) 
    into JSON-serializable dictionaries.
    """
    if hasattr(obj, 'to_dict'):
        return obj.to_dict()
    if hasattr(obj, '__dict__'):
        return obj.__dict__
    return obj


def get_and_refine_contract_code(address, w3, llm_client, model):
    address = w3.to_checksum_address(address)
    
    if address in KNOWN_CONTRACTS:
        print(f"  [*] Skipping decompilation for known contract: {KNOWN_CONTRACTS[address]}")
        return f"Known Protocol: {KNOWN_CONTRACTS[address]}"
    
    try:
        bytecode = w3.eth.get_code(address).hex()
    except Exception as e:
        return f"Error retrieving bytecode: {e}"
        
    if bytecode == '0x' or bytecode == '':
        return "EOA (Externally Owned Account) - No Contract Code"
    
    print(f"  [+] Unverified contract {address}. Initiating Panoramix decompilation...")
    
    try:
        result = subprocess.run(
            ['panoramix', bytecode], 
            capture_output=True, 
            text=True, 
            timeout=60
        )
        panoramix_pseudocode = result.stdout
        
        if not panoramix_pseudocode or "Error" in result.stderr:
            return f"Decompilation failed: {result.stderr or 'No readable output generated.'}"
            
    except Exception as e:
        return f"Panoramix execution error: {e}"

    if len(panoramix_pseudocode) > MAX_CODE_CHARS_PER_CONTRACT:
        print(f"  [!] Raw decompilation too large ({len(panoramix_pseudocode)} chars). Truncating to fit context window.")
        panoramix_pseudocode = panoramix_pseudocode[:MAX_CODE_CHARS_PER_CONTRACT] + "\n... [TRUNCATED DUE TO SIZE LIMITS] ..."

    print(f"  [+] Decompilation successful. Refining readability with Qwen3.5...")
    
    refinement_prompt = f"""
    You are an expert EVM reverse engineer. Below is a snippet of decompiled pseudocode generated by Panoramix.
    Please translate this into clean, highly readable, Solidity-like code. Maintain storage access patterns.
    
    RAW PANORAMIX OUTPUT:
    {panoramix_pseudocode}
    """
    
    try:
        response = llm_client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": refinement_prompt}]
        )
        content = response.choices[0].message.content
        if content is None:
            return panoramix_pseudocode
        return content
    except Exception as e:
        print(f"  [!] LLM refinement failed. Yielding raw Panoramix output. Error: {e}")
        return panoramix_pseudocode

def generate_transaction_bundle_json(tx_hashes, output_file="mev_bundle_data.json"):
    print(f"Starting Multi-Tx Extraction for {len(tx_hashes)} transactions...")
    
    detector = Detector(w3)
    analyzer = Analyzer()
    
    bundle_data = []
    unique_addresses = set()
    
    for idx, tx_hash in enumerate(tx_hashes):
        print(f"\nProcessing TX {idx + 1}/{len(tx_hashes)}: {tx_hash}")
        
        raw_trace = detector.get_transaction_trace(tx_hash)
        if not raw_trace:
            print(f"  [!] Failed to fetch traces for {tx_hash}. Skipping.")
            continue
            
        flat_traces = detector.parse_flat_traces(raw_trace)
        call_tree = analyzer.reconstruct_call_tree(flat_traces)
        
        all_execution_paths = analyzer.extract_execution_paths(call_tree)
        
        if len(all_execution_paths) > MAX_EXECUTION_PATHS_PER_TX:
            print(f"  [!] Explosive execution paths detected ({len(all_execution_paths)} paths). Truncating to top {MAX_EXECUTION_PATHS_PER_TX}.")
            all_execution_paths = all_execution_paths[:MAX_EXECUTION_PATHS_PER_TX]
            
        bundle_data.append({
            "sequence_order": idx + 1,
            "tx_hash": tx_hash,
            "call_tree": call_tree,
            "execution_paths": all_execution_paths
        })
        
    
        for t in flat_traces:
            if isinstance(t, dict):
                to_addr = t.get('to') or t.get('to_address')
            else:
                to_addr = getattr(t, 'to_address', None) or getattr(t, 'to', None)
            if to_addr:
                unique_addresses.add(to_addr)

    contracts_context = {}
    print(f"\nResolving {len(unique_addresses)} unique contract(s) across bundle...")
    for addr in unique_addresses:
        contracts_context[addr] = get_and_refine_contract_code(addr, w3, client, model_name)

    final_output = {
        "metadata": {
            "transaction_count": len(bundle_data),
            "unique_contracts_resolved": len(contracts_context)
        },
        "transactions": bundle_data,
        "contract_code": contracts_context
    }
    
    # Reverted back to saving and passing pretty-printed (indented) JSON
    json_string = json.dumps(final_output, indent=4, default=serialize_custom_objects)
    approx_tokens = len(json_string) / 4
    
    if approx_tokens > MAX_CONTEXT_TOKENS:
        print(f"\n  [!] CRITICAL WARNING: Generated JSON payload (~{int(approx_tokens)} tokens) exceeds safety limits.")
        print("  Applying emergency pruning to contract code fields...")
        for addr in final_output["contract_code"]:
            code_str = final_output["contract_code"][addr]
            if code_str and len(code_str) > 8000:
                final_output["contract_code"][addr] = code_str[:8000] + "\n... [TRUNCATED DUE TO SIZE LIMITS] ..."
        json_string = json.dumps(final_output, indent=4, default=serialize_custom_objects)

    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(json_string)
        
    print(f"\nExtraction complete! Data saved to {output_file}")
    return json_string


def generate_mev_analysis_report(json_payload, llm_client, model):
    print(f"\n[+] Sending bundle data to {model} for deep MEV analysis...")
    
    analysis_prompt = """You are an expert Blockchain Analyst and MEV (Maximal Extractable Value) Educator. 
    Your objective is to analyze a set of transaction data and clearly explain whether it represents an MEV strategy, classify the type of MEV, and break down exactly what happened in plain English.
    I am providing you with a JSON payload containing data extracted from one or more sequential Ethereum transactions. The JSON contains:
    - transactions: The complete transaction call trees and execution paths.
    - contract_code: Decompiled and refined (pseudocode/Solidity-like) logic for the unverified smart contracts interacted with during the execution.
    
    YOUR INSTRUCTIONS:
    Please analyze the provided data step-by-step and generate a clear, educational report following these phases:
    
    Phase 1: MEV Identification & Classification
    - Definitively state whether this transaction (or bundle of transactions) is related to MEV extraction.
    - If it is MEV, classify the specific type (e.g., Sandwich Attack, Atomic Arbitrage, Cross-DEX Arbitrage, Liquidation, JIT Liquidity, etc.).
    - Briefly define what this classification means for a reader who is trying to understand MEV concepts.
    
    Phase 2: The Actors & Environment
    - Identify the key players in the trace: The EOA (Externally Owned Account) initiating the transaction, the Bot/Router contract executing the logic, and any Victim(s) if applicable.
    - Identify the main protocols involved (e.g., Uniswap V2, WETH, Aave).
    
    Phase 3: Step-by-Step Transaction Explanation
    - Translate the highly technical execution traces and paths into a chronological, easy-to-read narrative.
    - Explain the flow of assets. For example: "The bot first used a flashloan to borrow 1,000 WETH. It then swapped this WETH for Token X on SushiSwap to drive the price up..."
    - Cross-reference this flow with the provided contract_code to explain how the bot's custom logic executed these steps.
    
    Phase 4: The Profit Mechanism & Builder Bribe
    - Explain exactly how the searcher (the bot operator) walked away with a profit. Which tokens did they accumulate by the end of the transaction?
    - Identify how the searcher paid the block builder/validator to get their transaction included (look for direct transfers to block.coinbase or high priority fees).
    
    OUTPUT FORMAT:
    Provide your response as a structured Markdown report. Use clear headings, bullet points, and concise explanations. Avoid overly dense bytecode jargon; aim to make the mechanics of the MEV strategy understandable to someone learning about blockchain dynamics."""

    full_message_content = f"{analysis_prompt}\n\n### PROVIDED JSON DATA PAYLOAD:\n{json_payload}"

    try:
        response = llm_client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": full_message_content}]
        )
        return response.choices[0].message.content
    except Exception as e:
        return f"An error occurred during the analysis phase: {e}"


if __name__ == "__main__":
    TX_BUNDLE = [
        "0x5d11f3d4df53eaf751278b74ad440ebb57423ecad65fd7d50183f3d2949a8f71",
        "0x2f9897fcfffe654f1882356ab55b3754503f4f570dac8def677a24e46e285958"
    ]
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    json_filename = f"mev_bundle_data_{timestamp}.json"
    report_filename = f"mev_analysis_report_{timestamp}.md"
    
    json_payload = generate_transaction_bundle_json(TX_BUNDLE, json_filename)
    
    analysis_report = generate_mev_analysis_report(json_payload, client, model_name)
    
    print("\n=======================================================")
    print("                MEV ANALYSIS REPORT                    ")
    print("=======================================================\n")
    print(analysis_report)
    
    with open(report_filename, "w", encoding="utf-8") as f:
        f.write(analysis_report)
        
    print(f"\n[+] Analytical report saved to: '{report_filename}'")