from framework.pipeline.parser import Parser
from framework.pipeline.detector import Detector
from framework.pipeline.extractor import Extractor
from framework.pipeline.analyzer import Analyzer
from framework.pipeline.reporter import Reporter
import json
import os
import subprocess
import google.generativeai as genai 
from web3 import Web3

# Initialize your Web3 connection
w3 = Web3(Web3.HTTPProvider('http://127.0.0.1:8504'))
genai.configure(api_key="YOURAPIKEY")
gemini_flash = genai.GenerativeModel('gemini-2.5-flash')

def serialize_custom_objects(obj):
    """
    Helper function to convert custom objects (like CallNode) 
    into JSON-serializable dictionaries.
    """
    return obj.__dict__ 

def get_and_refine_contract_code(address, w3, llm_model):
    """
    Fetches bytecode via the main Web3 connection, passes the RAW BYTECODE to Panoramix 
    (bypassing its internal RPC needs), and uses an LLM to refine readability.
    """
    address = w3.to_checksum_address(address)
    
    # 1. Fetch the bytecode using our reliable Web3 connection
    bytecode = w3.eth.get_code(address).hex()
    
    if bytecode == '0x' or bytecode == '':
        return "EOA (Externally Owned Account) - No Contract Code"
    
    print(f"  [+] Unverified contract {address}. Initiating Panoramix decompilation...")
    
    # 2. Run Panoramix Decompiler via subprocess, passing the BYTECODE directly
    try:
        # By passing the bytecode string instead of the address, 
        # Panoramix doesn't need to connect to the RPC node at all!
        result = subprocess.run(
            ['panoramix', bytecode], 
            capture_output=True, 
            text=True, 
            timeout=60
        )
        panoramix_pseudocode = result.stdout
        
        if not panoramix_pseudocode or "Error" in result.stderr:
            return f"Decompilation failed: {result.stderr}"
            
    except Exception as e:
        return f"Panoramix execution error: {e}"

    print(f"  [+] Decompilation successful. Refining readability with Gemini...")
    
    # 3. Refine readability using LLM
    refinement_prompt = f"""
    You are an expert EVM reverse engineer. Below is decompiled pseudocode generated by Panoramix from a smart contract. 
    It is currently difficult to read. 
    
    Please translate this into clean, highly readable, Solidity-like code. 
    Maintain all underlying logic, storage access patterns, and control structures. 
    Do not omit any functions.
    
    RAW PANORAMIX OUTPUT:
    {panoramix_pseudocode}
    """
    
    try:
        response = llm_model.generate_content(refinement_prompt)
        return response.text
    except Exception as e:
        print(f"  [!] LLM refinement failed. Yielding raw Panoramix output.")
        return panoramix_pseudocode

def generate_transaction_bundle_json(tx_hashes, output_file="mev_bundle_data.json"):
    """
    Extracts traces, call trees, and decompiled code for multiple transactions
    and exports them as a single JSON object.
    """
    print(f"Starting Multi-Tx Extraction for {len(tx_hashes)} transactions...")
    
    detector = Detector(w3)
    analyzer = Analyzer()
    
    bundle_data = []
    unique_addresses = set()
    
    # Extract and parse traces for ALL transactions
    for idx, tx_hash in enumerate(tx_hashes):
        print(f"\nProcessing TX {idx + 1}/{len(tx_hashes)}: {tx_hash}")
        
        raw_trace = detector.get_transaction_trace(tx_hash)
        if not raw_trace:
            print(f"  [!] Failed to fetch traces for {tx_hash}. Skipping.")
            continue
            
        flat_traces = detector.parse_flat_traces(raw_trace)
        call_tree = analyzer.reconstruct_call_tree(flat_traces)
        execution_paths = analyzer.extract_execution_paths(call_tree)
        
        bundle_data.append({
            "sequence_order": idx + 1,
            "tx_hash": tx_hash,
            "call_tree": call_tree, # Added call tree directly to output
            "execution_paths": execution_paths
        })
        
        # Aggregate unique addresses across the entire bundle
        for t in flat_traces:
            if t.get('to'):
                unique_addresses.add(t['to'])

    #Extract & Decompile Context for the entire bundle
    contracts_context = {}
    print(f"\nResolving {len(unique_addresses)} unique contract(s) across bundle...")
    for addr in unique_addresses:
        contracts_context[addr] = get_and_refine_contract_code(addr, w3, gemini_flash)

    #Package everything into a final JSON structure
    final_output = {
        "metadata": {
            "transaction_count": len(bundle_data),
            "unique_contracts_resolved": len(contracts_context)
        },
        "transactions": bundle_data,
        "contract_code": contracts_context
    }
    
    # Export to file
    with open(output_file, 'w', encoding='utf-8') as f:
        # ADDED 'default=serialize_custom_objects' HERE
        json.dump(final_output, f, indent=4, default=serialize_custom_objects)
        
    print(f"\nExtraction complete! Data saved to {output_file}")
    
    # ADDED 'default=serialize_custom_objects' HERE TOO
    return json.dumps(final_output, indent=4, default=serialize_custom_objects)


if __name__ == "__main__":
    # Example sequence representing a potential Sandwich Attack
    TX_BUNDLE = [
        "0x1af138ec5ce7d521a82ef780c54c6e0d05fc587846fe28dd8284d2f1e9a75b01", 
        "0xb93eca69ca2ac5e595a86c9ad01ba0828fb669cc5fea2ce2df31ba4cd79c7097",
        "0x912b223668ee16bb2f9312478c1a6c66f7172b4b7c2141551b27c6cd8dcdf586"  
    ]
    
    json_payload = generate_transaction_bundle_json(TX_BUNDLE, "mev_bundle_data.json")
    
    print("\nPreview of JSON Payload:")
    print(json_payload[:1000] + "\n... [TRUNCATED] ...")